login_system/routes.py
# Code responsible for the main routes of the WebApp

from flask import Blueprint, render_template, redirect, session


main = Blueprint('main', __name__)


@main.route('/')
def home():
    if 'logged_in' in session:
        return redirect('/dashboard/')
    else:
        return render_template('home.html')


@main.route('/dashboard/')
def dashboard():
    if 'logged_in' in session:
        return render_template('dashboard.html')
    else:
        return redirect('/')


@main.route('/update_user/')
def update_user():
    if 'logged_in' in session:
        return render_template('update_user.html')
    else:
        return redirect('/')


@main.route('/reset/')
def reset():
    if 'logged_in' in session:
        return redirect('/dashboard/')
    else:
        return render_template('reset.html')

login_system/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login System</title>

    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/styles.css">

</head>

<body>
    
    {% block content %}
    {% endblock %}

    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/scripts.js"></script>
</body>

</html>

login_system/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="card-wrapper">
    <div class="card">
        <h1 class="center">Dashboard</h1>
        <p class="center">You are currently logged in.</p>
        <div class="center">
            <a href="/user/logout/" class="btn btn--secondary">Sign out</a>
        </div>
    </div>
    <div class="card">
        <h2 class="center">Your Info</h2>
        <p class="center">
            <strong>ID:</strong> {{ session['user']['_id'] }}<br>
            <strong>Username:</strong> {{ session['user']['username'] }}<br>
            <strong>Name:</strong> {{ session['user']['name'] }}<br>
            <strong>Email:</strong> {{ session['user']['email'] }}<br>
            <br>
            <a class="btn" href="{{ url_for('main.update_user') }}">Update Info</a>
        </p>
    </div>
</div>

{% endblock %}

login_system/templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="card-wrapper">

    <div class="card">
        <h1 class="center">Create an Account</h1>
        <form name="signup_form">
            <label for="name">Name</label>
            <input type="text" name="name" class="field" required>

            <label for="username">Username</label>
            <input type="text" name="username" class="field" required>

            <label for="email">Email</label>
            <input type="email" name="email" class="field" required>

            <label for="password">Password</label>
            <input type="password" name="password" class="field" required>

            <p class="error error--hidden"></p>

            <input type="submit" value="Sign up" class="btn">
        </form>
    </div>

    <div class="card">
        <h1 class="center">Log In</h1>
        <form name="login_form">
            <label for="email">Username</label>
            <input type="text" name="username" class="field" required>

            <label for="password">Password</label>
            <input type="password" name="password" class="field" required>

            <p class="error error--hidden"></p>

            <input type="submit" value="Log in" class="btn">
            <div class="center">
                <a class="center" href="{{ url_for('main.reset') }}">Need help to login?</a>
            </div>
        </form>
    </div>

</div>

{% endblock %}

login_system/templates/reset.html
{% extends "base.html" %}

{% block content %}

<div class="card-wrapper">

    <div class="card">
        <h1 class="center">Reset your password and username</h1>
        <form name="reset_form">
            <label for="email">Email</label>
            <input type="email" name="email" class="field" required>

            <label for="name">Username</label>
            <input type="text" name="username" class="field" required>

            <label for="password">Password</label>
            <input type="password" name="password" class="field" required>

            <p class="error error--hidden"></p>

            <input type="submit" value="Reset" class="btn">
            <div class="center">
                <a class="btn btn--secondary" href="{{ url_for('main.home') }}">Voltar</a>
            </div>
        </form>
    </div>

</div>

{% endblock %}

login_system/templates/update_user.html
{% extends "base.html" %}

{% block content %}

<div class="card-wrapper">
    <div class="card">
        <h1 class="center">Update your info</h1>
        <form name="update_user">
            <label for="name">Name</label>
            <input type="text" name="name" class="field"  value="{{ session['user']['name'] }}" required>

            <label for="username">Username</label>
            <input type="text" name="username" class="field" value="{{ session['user']['username'] }}" required>

            <label for="email">Email</label>
            <input type="email" name="email" class="field" value="{{ session['user']['email'] }}" required>

            <label for="password">Password</label>
            <input type="password" name="password" class="field" required>

            <p class="error error--hidden"></p>

            <input type="submit" value="Update" class="btn">
        </form>
        <div class="center">
            <a class="btn btn--secondary" href="{{ url_for('main.home') }}">Voltar</a>
        </div>

    </div>
</div>

{% endblock %}